insert into insurerdetails( INSURER_ID,  DISBURSEMENTDURATION,  INSURERAMOUNTLIMIT, INSURERNAME
,  INSURERPACKAGENAME)values (1001,4,3000,'SBI','BRONZE');

insert into insurerdetails( INSURER_ID,  DISBURSEMENTDURATION,  INSURERAMOUNTLIMIT, INSURERNAME
,  INSURERPACKAGENAME)values (1002,6,2000,'SBI','SILVER');


insert into insurerdetails( INSURER_ID,  DISBURSEMENTDURATION,  INSURERAMOUNTLIMIT, INSURERNAME
,  INSURERPACKAGENAME)values (1003,8,1000,'SBI','GOLD');

insert into insurerdetails( INSURER_ID,  DISBURSEMENTDURATION,  INSURERAMOUNTLIMIT, INSURERNAME
,  INSURERPACKAGENAME)values (1004,8,1500,'HDFC','GOLDJUBLIE');

insert into insurerdetails( INSURER_ID,  DISBURSEMENTDURATION,  INSURERAMOUNTLIMIT, INSURERNAME
,  INSURERPACKAGENAME)values (1005,8,1800,'HDFC','SILVERJUBLIE');








